name: Update Crowdin files
on:
  push:
    branches:
      - action-**

jobs:
  updateCrowdin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Update Crowdin based on pushed commit
      uses: ./.github/actions/crowdin-updater